accounts/urls.py
from django.contrib.auth.urls import *
from django.urls import reverse_lazy

from . import views as accounts_views

app_name = 'accounts'

urlpatterns = [
                  path('personl_info_update/<int:pk>/', accounts_views.PersonalInfoUpdateView.as_view(),
                       name='personal_info_update'),
                  path('email_verification/', accounts_views.EmailVerification.as_view(), name='email_verification'),
                  path('verify_email/<uidb64>/<token>/', accounts_views.EmailVerificationLinkCheckView.as_view(),
                       name='link_verification'),
                  path('verification-successful/', accounts_views.EmailVerificationSuccess.as_view(),
                       name='verification_success'),
                  path('profile/', accounts_views.ProfileView.as_view(), name='profile'),
                  path('signup/', accounts_views.SignupView.as_view(), name='signup'),
                  path('delete-account/', accounts_views.DeleteAccountView.as_view(), name='delete_account'),
                  path('delete-success/', accounts_views.DeleteSuccessView.as_view(), name='delete_success'),
                  path('ordre-list/', accounts_views.OrderListView.as_view(), name='order-list'),
                  path('password_change/',
                       views.PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')),
                       name='password_change'),
                  path('password_reset/',
                       views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
                       name='password_reset'),
                  path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(
                      success_url=reverse_lazy('accounts:password_reset_complete')),
                       name='password_reset_confirm'),
              ] + urlpatterns

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products.views import ProductListView


urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', ProductListView.as_view(), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager as BaseUserManager
from django.db import models
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError
        if not password:
            raise ValueError
        user = self.model(
            email=self.normalize_email(email),
            **extra_fields
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        if not extra_fields.setdefault('is_staff', True):
            raise ValueError
        if not extra_fields.setdefault('is_superuser', True):
            raise ValueError
        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    username = models.CharField(_('username'), max_length=128, blank=True)
    is_staff = models.BooleanField(_('staff status'), default=False,
                                   help_text=_('Designates whether the user can log into this admin site'))
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_(
                                        'Designates whether this user should be treated as active. '
                                        'Unselect this instead of deleting accounts.'
                                    ))
    date_joined = models.DateTimeField(_('date joined'), auto_now_add=True)

    USERNAME_FIELD = 'email'
    EMAIL_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def __str__(self):
        return self.email

    @property
    def is_admin(self):
        return self.is_superuser


class Customer(User):
    verified_email = models.BooleanField(default=False)

    def verify(self):
        self.verified_email = True
        self.save()

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Customer

User = get_user_model()


class SignupForm(UserCreationForm):
    class Meta:
        model = Customer
        fields = 'email',

accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.http import Http404
from django.shortcuts import redirect
from django.template import loader
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.views.generic import CreateView, TemplateView, DeleteView, ListView, View, UpdateView

from ecommerce.utils import EmailVerificationTokenGenerator
from .forms import SignupForm
from .models import Customer

User = get_user_model()


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'
    #  todo implement this view
    pass


class SignupView(CreateView):
    form_class = SignupForm
    model = Customer
    success_url = reverse_lazy('accounts:login')


class EmailVerification(TemplateView):
    template_name = 'accounts/email_verification_send.html'

    def get(self, request, *args, **kwargs):
        customer = request.user.customer
        if not customer.verified_email:
            current_site = get_current_site(request)
            context = {
                'email': customer.email,
                'domain': current_site.domain,
                'site_name': current_site.name,
                'uid': urlsafe_base64_encode(force_bytes(customer.id)),
                'user': customer,
                'token': EmailVerificationTokenGenerator().make_token(customer),
                'protocol': 'http'
            }
            body = loader.render_to_string('accounts/verification_email_template.html', context)
            send_mail(
                subject=f'Email verification at {current_site.name}',
                message=body,
                from_email='hiahmadyan@gmail.com',
                recipient_list=[customer.email, ]
            )
            return super().get(request, *args, **kwargs)
        raise Http404


class EmailVerificationLinkCheckView(View):
    def dispatch(self, *args, **kwargs):
        self.customer = self.get_user(kwargs.get('uidb64'))
        if self.customer is not None:
            token = kwargs.get('token')
            if token:
                if EmailVerificationTokenGenerator().check_token(self.customer, token):
                    self.customer.verify()
                    return redirect('accounts:verification_success')
        raise Http404

    def get_user(self, uidb64):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            customer = Customer.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, Customer.DoesNotExist, ValidationError):
            customer = None
        return customer


class EmailVerificationSuccess(TemplateView):
    template_name = 'accounts/verification_successful.html'


class DeleteAccountView(LoginRequiredMixin, DeleteView):
    success_url = reverse_lazy('accounts:delete_success')

    def get_object(self, queryset=None):
        return self.request.user.customer


class DeleteSuccessView(TemplateView):
    template_name = 'accounts/delete_success.html'


class OrderListView(ListView):
    # todo implement this view with Order model
    def get_queryset(self):
        return self.queryset.filter(user=self.request.user)


class PersonalInfoUpdateView(UpdateView):
    model = Customer
    fields = 'username',
    success_url = reverse_lazy('accounts:profile')

accounts/templates/accounts/customer_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
    <div class="mt-5">
        <div class="container text-center">
            <form action="" method="POST">
                {% csrf_token %}
                <h4>Are you sure to delete your account!!??</h4>
                <input type="submit" class="btn btn-danger" value="Yes">
                <a href="{% url 'accounts:profile' %}">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/customer_form.html
{% extends 'base.html' %}


{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-4">
            {% include 'base_form.html' with submit_value="Create" %}
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/delete_success.html
{% extends 'base.html' %}



{% block content %}
    <div class="container text-center">
        <div class="mt-5">
            <h3>We wish you best!!</h3>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/email_verification_send.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center mt-5">
<h5>Email has been send to your email account! please check your email!</h5>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}


{% block content %}
    <div class="row mt-5">
        <div class="col-1 col-md-3"></div>
        <div class="col-6 bg-info">
            <p class="my-auto py-2 rounded">Welcome <strong>{{ request.user.username }}</strong></p>
        </div>
    </div>
    {% if not request.user.customer.verified_email %}
        <div class="row justify-content-center mt-3">
            <div class="col-6">
                <div class="bg-light p-1 rounded">
                    <form action="{% url 'accounts:email_verification' %}">
                        <h5 class=" my-auto">please click on <input type="submit" value="Here" class="btn btn-warning">
                            to send the Email verification link</h5>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
    <div class="row justify-content-center mt-5 px-3">
        <div class="col-2">
            <a href="{% url 'accounts:personal_info_update' pk=request.user.customer.pk %}" class="">
                <div class="profile-card">
                    <h5 class="">Edit personal Info</h5>
                </div>
            </a>
        </div>
        <div class="col-2">
            <a href="{% url 'accounts:password_reset' %}">
                <div class="profile-card">
                    <h5 class="">reset password</h5>
                </div>
            </a>
        </div>
        <div class="col-2">
            <a href="{% url 'accounts:password_change' %}" class="">
                <div class="profile-card">
                    <h5 class="">change password</h5>
                </div>
            </a>
        </div>
        <div class="col-2">
            <a href="" class="">
                <div class="profile-card">
                    <h5 class=:">change email</h5>
                </div>
            </a>
        </div>
        <div class="col-2">
            <a href="{% url 'accounts:order-list' %}" class="">
                <div class="profile-card">
                    <h5 class="">orders</h5>
                </div>
            </a>
        </div>
        <div class="col-2">
            <a href="{% url 'accounts:delete_account' %}" class="">
                <div class="profile-card">
                    <h5 class="">Delete Account</h5>
                </div>
            </a>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/user_confirm_delete.html
{% extends 'base.html' %}


{% block content %}
    <div class="mt-5">
        <div class="container text-center">
            <form action="" method="POST">
                {% csrf_token %}
                <h4>Are you sure to delete your account!!??</h4>
                <input type="submit" class="btn btn-danger" value="Yes">
                <a href="{% url 'accounts:profile' %}">Cancel</a>
            </form>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/user_form.html
{% extends 'base.html' %}


{% block content %}
    <div class="row justify-content-center mt-5">
        <div class="col-4">
            {% include 'base_form.html' with submit_value="Create" %}
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/verification_email_template.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a verification email for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:link_verification' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

accounts/templates/accounts/verification_successful.html
{% extends 'base.html' %}

{% block content %}
<div class="text-center">
<h5>Congratulation your email has been verified</h5>
</div>
{% endblock %}