accounts/urls.py
from django.contrib.auth.urls import *
from django.urls import reverse_lazy

from . import views as accounts_views

app_name = 'accounts'

urlpatterns = [
                  path('personl_info_update/<int:pk>/', accounts_views.PersonalInfoUpdateView.as_view(),
                       name='personal_info_update'),
                  path('email_verification/', accounts_views.EmailVerification.as_view(), name='email_verification'),
                  path('verify_email/<uidb64>/<token>/', accounts_views.EmailVerificationLinkCheckView.as_view(),
                       name='link_verification'),
                  path('verification-successful/', accounts_views.EmailVerificationSuccess.as_view(),
                       name='verification_success'),
                  path('profile/', accounts_views.ProfileView.as_view(), name='profile'),
                  path('signup/', accounts_views.SignupView.as_view(), name='signup'),
                  path('delete-account/', accounts_views.DeleteAccountView.as_view(), name='delete_account'),
                  path('delete-success/', accounts_views.DeleteSuccessView.as_view(), name='delete_success'),
                  path('ordre-list/', accounts_views.OrderListView.as_view(), name='order-list'),
                  path('password_change/',
                       views.PasswordChangeView.as_view(success_url=reverse_lazy('accounts:password_change_done')),
                       name='password_change'),
                  path('password_reset/',
                       views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
                       name='password_reset'),
                  path('reset/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(
                      success_url=reverse_lazy('accounts:password_reset_complete')),
                       name='password_reset_confirm'),
              ] + urlpatterns

ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from products.views import ProductListView


urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('', ProductListView.as_view(), name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/customStyle.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="/">E-Commerce</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if request.user.is_authenticated %}
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:profile' %}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                    </li>

                {% else %}
                     <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:signup' %}">SignUp</a>
                    </li>
                {% endif %}

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

{% block content %}

{% endblock %}

<scritp src="{% static 'js/bootstrap.js' %}"></scritp>
</body>
</html>

templates/base_form.html
{% load django_bootstrap5 %}


<form action="{{ action_url }}" method="{{ method|default:"Post" }}">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" value="{{ submit_value|default:"submit" }}" class="btn btn-success">
    <a href="{% url 'accounts:profile' %}" class="btn btn-primary">Cancel</a>
</form>